#:import menu menu
MainWidget:

<MainWidget>
    canvas.before:
        Rectangle:
            size: self.size
            source: './images/game_bg2.png'
    menu_widget: menu_widget
    perspective_point_x: self.width / 2
    perspective_point_y: self.height * .75

    MenuWidget:
        id: menu_widget
    Label:
        font_name: './fonts/AGOXES.ttf'
        font_size: dp(20)
        size_hint: .2, .2
        pos_hint: {'x': 0, 'top': 1}
        text: root.title_score